m4_include(header.js)
m4_include(pageAll.js)
m4_include(puppets.js)
m4_include(pageRegion.js)
m4_include(pageNewspaper.js)
m4_include(pageNewspaperEditor.js)
m4_include(pageRegionalDispatch.js)
m4_include(basic.js)
