function newspaperEditor() {
    var newspaperSettings = {};
    if ($("textarea[name=\"message\"]").val().split("\n").length >= 3)
        newspaperSettings = JSON.parse(atob($("textarea[name=\"message\"]").val().split("\n")[2]));

    //Create fields
    $("<tr></tr>").append($('<td class="leftside">Newspaper Title:</td>')).append($("<td></td>").append($('<input id="settingTitle">').keyup(updateNewspaperJSON))).insertBefore($("textarea[name=\"message\"]").parent().parent());
    $("<tr></tr>").append($('<td class="leftside">Dispatch Owner:</td>')).append($("<td></td>").append($('<input id="settingSubmitTo">').keyup(updateNewspaperJSON))).insertBefore($("textarea[name=\"message\"]").parent().parent());

    //Populate fields
    $("#settingTitle").val(newspaperSettings.title ? newspaperSettings.title : "");
    $("#settingSubmitTo").val(newspaperSettings.submitTo ? newspaperSettings.submitTo : "");
}

function updateNewspaperJSON() {
    var json = "{";
    json += '"title":"' + $("#settingTitle").val() + '",';
    json += '"submitTo":"' + $("#settingSubmitTo").val() + '"';
    json += "}";

    $("textarea[name=\"message\"]").val("This dispatch is automatically generated by LibreNS++ (http://forum.nationstates.net/viewtopic.php?f=15&t=304199). Edit manually at your own risk!\n\n" + btoa(json));
}
