var newspaperSettings = {};

function newspaperEditor() {
    if ($("textarea[name=\"message\"]").val().split("\n").length >= 3)
        newspaperSettings = JSON.parse(atob($("textarea[name=\"message\"]").val().split("\n")[2]));

    //Create fields
    $("<tr></tr>").append($('<td class="leftside">Newspaper Title:</td>')).append($("<td></td>").append($('<input id="settingTitle">').keyup(updateNewspaperJSON))).insertBefore($("textarea[name=\"message\"]").parent().parent());
    $("<tr></tr>").append($('<td class="leftside">Dispatch Owner:</td>')).append($("<td></td>").append($('<input id="settingSubmitTo">').keyup(updateNewspaperJSON))).insertBefore($("textarea[name=\"message\"]").parent().parent());
    $("<tr></tr>").append($('<td class="leftside">Newspaper Entries:</td>')).append($("<td></td>").append($('<select id="settingNewspaperEntries"><option value="new" selected>-- New Entry --</option></select>').change(entryEditor))).insertBefore($("textarea[name=\"message\"]").parent().parent());
    $("<tr></tr>").append($('<td class="leftside">Entry Title:</td>')).append($("<td></td>").append($('<input id="entryTitle">'))).insertBefore($("textarea[name=\"message\"]").parent().parent());
    $("<tr></tr>").append($('<td class="leftside">Entry Content:</td>')).append($("<td></td>").append($('<textarea id="entryContent" rows="18" wrap="soft">'))).insertBefore($("textarea[name=\"message\"]").parent().parent());
    $("<tr></tr>").append($('<td class="leftside"></td>')).append($("<td></td>").append($('<input type="button" value="Save Entry">').click(updateNewspaperEntry)).append($('<input type="button" value="Delete Entry">').click(deleteNewspaperEntry))).insertBefore($("textarea[name=\"message\"]").parent().parent());

    //Populate fields
    $("#settingTitle").val(newspaperSettings.title ? newspaperSettings.title : "");
    $("#settingSubmitTo").val(newspaperSettings.submitTo ? newspaperSettings.submitTo : "");
    populateEntries();

    entryEditor();
}

function populateEntries() {
    if (!newspaperSettings.posts) {
        newspaperSettings.posts = {};
    }
    $("#settingNewspaperEntries").html('<option value="new" selected>-- New Entry --</option>');
    for (var i = 0; i < newspaperSettings.posts.length; i++) {
        $("#settingNewspaperEntries").append($('<option value="' + i + '">' + newspaperSettings.posts[i].title + '</option>'));
    }
    $("#settingNewspaperEntries").attr("size", newspaperSettings.posts.length + 2);
}

function entryEditor() {
    if ($("#settingNewspaperEntries").val() == "new") {
        $("#entryTitle").val("Untitled Entry");
        $("#entryContent").val("New Entry");
    } else {
        $("#entryTitle").val(newspaperSettings.posts[parseInt($("#settingNewspaperEntries").val())].title);
        $("#entryContent").val(newspaperSettings.posts[parseInt($("#settingNewspaperEntries").val())].content);
    }
}

function updateNewspaperEntry() {
    if ($("#settingNewspaperEntries").val() == "new") {
        newspaperSettings.posts.push({
            "title": $("#entryTitle").val(),
            "content": $("#entryContent").val()
        });
        populateEntries();
        updateNewspaperJSON();
    } else {
        newspaperSettings.posts[parseInt($("#settingNewspaperEntries").val())].title = $("#entryTitle").val();
        newspaperSettings.posts[parseInt($("#settingNewspaperEntries").val())].content = $("#entryContent").val();
        populateEntries();
        updateNewspaperJSON();
    }
}

function deleteNewspaperEntry() {
    if ($("#settingNewspaperEntries").val() != "new") {
        newspaperSettings.posts.splice(parseInt($("#settingNewspaperEntries").val()), 1);
        populateEntries();
        updateNewspaperJSON();
    }
}

function updateNewspaperJSON() {
    var json = "{";
    json += '"title":"' + $("#settingTitle").val() + '",';
    json += '"submitTo":"' + $("#settingSubmitTo").val() + '",';
    json += '"posts":' + JSON.stringify(newspaperSettings.posts);
    json += "}";

    $("textarea[name=\"message\"]").val("This dispatch is automatically generated by LibreNS++ (http://forum.nationstates.net/viewtopic.php?f=15&t=304199). Edit manually at your own risk!\n\n" + btoa(json));
}
